### ISSUE TITLE
python manage.py runserver 80 Error

### ISSUE THREAD

**Issue by alinemone** [Faral-Ghaemi/FaraPy#2]
(env) λ python manage.py runserver 80
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Alinemone\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Alinemone\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Alinemone\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1064, in get_code
  File "<frozen importlib._bootstrap_external>", line 513, in _classify_pyc
ImportError: bad magic number in 'blog.models': b'a\r\r\n'
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 598, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 583, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 301, in run
    self.run_loop()
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 307, in run_loop
    next(ticker)
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 347, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 363, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 262, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 103, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\Alinemone\Desktop\FaraPy-main\FaraPy-main\env\lib\site-packages\django\utils\autoreload.py", line 139, in iter_modules_and_files
    if not path.exists():
  File "C:\Users\Alinemone\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1391, in exists
    self.stat()
  File "C:\Users\Alinemone\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1197, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap_external>'

**Comment by Faral-Ghaemi** [comment]
Hey Ali.
You try to use a virtual environment and I think you cant install all of the libraries. so you should use main python for this project and follow our steps for installation
.

**Comment by alirezakhoramimn** [comment]
Hi i think you accidentally deleted the Farapy.urls.py file
`python3 manage.py runserver 800
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alireza-lap/.local/lib/python3.8/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/alireza-lap/.local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/alireza-lap/.local/lib/python3.8/site-packages/django/core/management/base.py", line 387, in check
    all_issues = self._run_checks(
  File "/home/alireza-lap/.local/lib/python3.8/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/alireza-lap/.local/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/alireza-lap/.local/lib/python3.8/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/alireza-lap/.local/lib/python3.8/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/alireza-lap/.local/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/alireza-lap/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/alireza-lap/.local/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/alireza-lap/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'FaraPy.urls'`

**Comment by Faral-Ghaemi** [comment]
you must use python 3.9

**Comment by alirezakhoramimn** [comment]
> you must use python 3.9

Could you add support for the previous versions as well?
